version: "2.4"
services:
  
  server:
    container_name: airsonic_server
    image: airsonicadvanced/airsonic-advanced:latest
    user: "910:910"
    volumes:
      - /srv/airsonic/server:/var/airsonic
      - /srv/airsonic/music:/var/music
      - /srv/airsonic/podcasts:/var/podcasts
      - /srv/airsonic/playlists:/var/playlists
    environment:
      JAVA_OPTS: "-Xmx256M"
    mem_limit: 1G
    memswap_limit: 1G
    restart: "always"

  proxy:
    container_name: airsonic_proxy
    image: local/nginx-proxy
    pull_policy: never
    user: "911:901"
    ports:
      - "2010:8080"
    volumes:
      - /srv/airsonic/proxy:/var/log/nginx
    environment:
      SERVER_NAME: "localhost"
      SERVER_PORT: 2010
      UPSTREAM: "server:4040"
    mem_limit: 16M
    memswap_limit: 16M
    restart: "always"
